########################################################################################################################
########################################################################################################################
##                                                      Winstreak Addon                                               ##
########################################################################################################################
########################################################################################################################

##Version
##Don't change this!
version:

##storageSystem

storage:
  use-mysql: false
  host:
  port:
  username:
  password:
  database:

settings:
  kick-when-failed-to-register-a-player: true
  kick-on-failed-message: "[Winstrak] &cUnable to register/load your user on/from database!"